apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: phoenix-app-release  # Name of the HelmRelease
  namespace: default          # Ensure this matches the namespace where you want to deploy the chart
spec:
  interval: 5m                # How often Flux should check for updates
  chart:
    spec:
      chart: phoenix-app      # Chart name as listed in the index.yaml
      version: "1.1.2"        # Specific chart version to deploy
      sourceRef:
        kind: HelmRepository
        name: my-pheonix-app # References the HelmRepository created above
        namespace: default    # Namespace must match the HelmRepository's namespace
  values:
   replicaCount: 2                  
