apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudnative-pg  # Name of the HelmRelease
  namespace: default          # Ensure this matches the namespace where you want to deploy the chart
spec:
  interval: 5m                # How often Flux should check for updates
  chart:
    spec:
      chart: cloudnative-pg      # Chart name as listed in the index.yaml
      version: "0.20.2"        # Specific chart version to deploy
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg # References the HelmRepository created above
        namespace: default    # Namespace must match the HelmRepository's namespace
  values:
    postgesql:
     authentication:
       superuser: postgres
       password: supersecret
                         
