apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      containers:
      - name: postgres-exporter
        image: wrouesnel/postgres_exporter
        args:
          - "--extend.query-path=/etc/postgres-exporter/custom-queries.yaml"
        ports:
        - containerPort: 9187
        envFrom:
        - configMapRef:
            name: postgres-exporter-config
        volumeMounts:
        - name: custom-queries
          mountPath: /etc/postgres-exporter
        securityContext:
          runAsUser: 0  # Run the container as root user
      volumes:
      - name: custom-queries
        configMap:
          name: pg-custom-queries
