apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "58.2.2" 
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
   
