apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      # version: "2.8.0"  # Check for the latest version on the Grafana Helm repo
      sourceRef:
        kind: HelmRepository
        name: loki-prom
        namespace: default
  values:
    config:
      auth_enabled: false
      server:
        http_listen_port: 3100
      schema_config:
        configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
      storage_config:
        boltdb_shipper:
          active_index_directory: /data/loki/index
          cache_location: /data/loki/cache
          cache_ttl: 24h
          shared_store: filesystem
        filesystem:
          directory: /data/loki/chunks
