apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: my-pheonix-app   # Changed from 'example-repo' to 'my-pheonix-app'
  namespace: default     # Changed from 'flux-system' to 'default'
spec:
  interval: 1m
  url: "curl https://github.com/dhanunjayareddy/helm-ch/index.yaml"  # Updated URL to point to your GitHub repository

