apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-pheonix-app   # Name of the HelmRelease
  namespace: default             # Same namespace as specified for the HelmRepository
spec:
  interval: 5m                   # Sync interval
  chart:
    spec:
      chart: my-pheonix-app      # Assuming the chart name is the same as the repository name
      version: "1.0.0"           # Specify the version of the chart you want to deploy
      sourceRef:
        kind: HelmRepository
        name: my-pheonix-app     # Name must match the HelmRepository metadata.name
        namespace: default       # Namespace must match HelmRepository's namespace
  values:
    key: value                   # Example placeholder for actual values needed for the chart

